import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
import assert from 'node:assert/strict';
const backend=spawn(process.env.JAVA_HOME?process.env.JAVA_HOME+'/bin/java':'java',['-jar','../backend/target/gymlog-1.0.0.jar'],{env:{...process.env,PORT:'18081',DB_URL:process.env.TEST_DB_URL||'jdbc:h2:mem:e2e;DB_CLOSE_DELAY=-1'},stdio:'ignore'});
const frontend=spawn('./node_modules/.bin/ng',['serve','--host','127.0.0.1','--proxy-config','proxy.e2e.json','--port','14200'],{stdio:'ignore',detached:true});let browser;
try{
for(let i=0;i<60;i++){try{const r=await fetch('http://127.0.0.1:14200/api/auth/csrf');if(r.ok)break;}catch{}await delay(500);}
browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];await page.addInitScript(()=>{window.__csp=[];document.addEventListener('securitypolicyviolation',e=>window.__csp.push(e.violatedDirective+':'+e.blockedURI));});page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.PRODUCTION?'http://127.0.0.1:18081':'http://127.0.0.1:14200');assert.equal(await page.locator('header').evaluate(e=>getComputedStyle(e).display),'flex','CSS must be loaded');await page.getByRole('button',{name:'Crear una cuenta',exact:true}).click();await page.getByLabel('Usuario',{exact:true}).fill('alice');await page.getByLabel('Contraseña',{exact:true}).fill('E2E-test-password-only');await page.getByRole('button',{name:'Crear cuenta',exact:true}).click();await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.getByRole('button',{name:'Añadir ejemplo',exact:true}).waitFor();
if(process.env.OCR_IMAGE){await page.getByRole('button',{name:'Rutina',exact:true}).click();await page.locator('input[type=file]').first().setInputFiles(process.env.OCR_IMAGE);await page.getByText('Texto leído en este dispositivo.',{exact:false}).waitFor({timeout:120000});const ocr=await page.getByLabel('Texto leído o pegado').inputValue();assert.ok(ocr.includes('Press')||ocr.includes('PRESS'));await page.getByRole('button',{name:'Convertir en borrador editable'}).click();await page.getByText('5 borradores por revisar.',{exact:false}).waitFor();await page.getByRole('button',{name:'Cancelar',exact:true}).click();console.log('OCR passed: photo recognized, 5 day drafts, no auto-save');}await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.getByRole('button',{name:'Añadir ejemplo',exact:true}).click();await page.getByRole('button',{name:'Empezar sesión'}).waitFor();await page.getByRole('button',{name:'Rutina',exact:true}).click();await page.getByLabel('Lunes',{exact:true}).selectOption({label:'Rutina de ejemplo'});await page.getByRole('button',{name:'Guardar semana'}).click();await page.getByText('Semana guardada. Cada día verás qué toca.').waitFor();await page.getByRole('button',{name:'Inicio',exact:true}).click();assert.equal(await page.locator('nav').evaluate(e=>getComputedStyle(e).position),'fixed');await page.screenshot({path:'../docs/mobile-home.png',fullPage:true});await page.getByRole('button',{name:'Ver calendario completo'}).click();await page.getByLabel('Rutina para este día').selectOption({label:'Rutina de ejemplo'});await page.getByRole('button',{name:'Guardar día',exact:true}).click();await page.getByRole('button',{name:'Entrenar este día'}).waitFor();await page.getByRole('button',{name:'Entrenar este día'}).click();
await page.getByLabel('Peso Press de banca serie 1',{exact:true}).fill('42.5');await page.getByRole('button',{name:'Completar Press de banca serie 1',exact:true}).click();await page.screenshot({path:'../docs/mobile-session.png',fullPage:true});await page.reload();await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.getByRole('button',{name:'Terminar y guardar sesión'}).waitFor();assert.equal(await page.getByLabel('Peso Press de banca serie 1',{exact:true}).inputValue(),'42.5');
page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Terminar y guardar sesión'}).click();await page.getByText('1 series · Ver entrenamiento').waitFor();await page.getByRole('button',{name:'Progreso',exact:true}).click();await page.getByText('TU RÉCORD REGISTRADO').waitFor();
await page.screenshot({path:'../docs/mobile-progress.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'../docs/desktop-progress.png',fullPage:true});await page.setViewportSize({width:390,height:844});const privateState=await page.evaluate(async()=>await(await fetch('/api/state')).json());assert.equal(privateState.workouts[0].sets[0].weight,42.5);const privateId=privateState.routines[0].id;
await page.getByRole('button',{name:'alice · Salir'}).click();await page.getByLabel('Usuario',{exact:true}).fill('alice');await page.getByLabel('Contraseña',{exact:true}).fill('E2E-test-password-only');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.getByRole('button',{name:'alice · Salir'}).waitFor();await page.getByRole('button',{name:'alice · Salir'}).click();await page.getByRole('button',{name:'Crear una cuenta',exact:true}).click();await page.getByLabel('Usuario',{exact:true}).fill('bob');await page.getByLabel('Contraseña',{exact:true}).fill('E2E-test-password-only');await page.getByRole('button',{name:'Crear cuenta',exact:true}).click();await page.getByRole('button',{name:'Entrenar',exact:true}).click();await page.getByText('Tu primera rutina empieza aquí').waitFor();
const isolated=await page.evaluate(async()=>await(await fetch('/api/state')).json());assert.equal(isolated.workouts.length,0);assert.equal(isolated.routines.length,0);assert.equal(isolated.plans.length,0);assert.equal(isolated.weekly.length,0);
const denied=await page.evaluate(async(id)=>{const t=await(await fetch('/api/auth/csrf')).json();return (await fetch('/api/routines/'+id,{method:'DELETE',headers:{[t.header]:t.token}})).status;},privateId);assert.equal(denied,404);
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal overflow at '+width);}
await page.getByRole('button',{name:'Inicio',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../docs/mobile-empty.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'../docs/desktop-home.png',fullPage:true});const privateWeekly=privateState.weekly;assert.equal(privateWeekly.length,7);await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../docs/mobile-empty.png',fullPage:true});assert.deepEqual(await page.evaluate(()=>window.__csp),[],'No CSP violations');assert.deepEqual(errors,[]);console.log('PASS v2: register, secure session, calendar, workout, reload draft, history, chart, logout, second account isolation, IDOR denied, responsive');
}finally{await browser?.close();backend.kill();try{process.kill(-frontend.pid,'SIGTERM')}catch{}}
