import {parseRoutine,parseRoutines} from './photo-parser.mjs';
import {createWorker} from 'tesseract.js';
import {volume,maximum,validSet} from './metrics.mjs';
import 'zone.js';
import {bootstrapApplication} from '@angular/platform-browser';
import {Component,OnInit,provideZoneChangeDetection,ChangeDetectorRef,inject,ChangeDetectionStrategy} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {CommonModule} from '@angular/common';
interface Exercise {id?:string;name:string;sets:number;reps:number;repsMax:number;unit:string;perSide:boolean;rir:string}
interface Routine {id?:string;name:string;exercises:Exercise[]}
interface SetLog {exercise:string;weight:number;reps:number;unit:string;perSide:boolean;rir:number;done?:boolean}
interface Workout {id?:string;routine:string;date:string;notes:string;sets:SetLog[]}
interface Plan {date:string;routineId:string|null}
interface State {routines:Routine[];workouts:Workout[];plans:Plan[];weekly?:{weekday:number;routineId:string|null}[]}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
@Component({changeDetection:ChangeDetectionStrategy.Default,selector:'gym-app',standalone:true,imports:[FormsModule,CommonModule],templateUrl:'./app.html'})
class App implements OnInit {
 cdr=inject(ChangeDetectorRef);todayDate=today();newDateDay=new Date().getDay();
 user:{id:string;username:string}|null=null;authMode='login';credentials={username:'',password:''};csrf={token:'',header:'X-CSRF-TOKEN'};photoDrafts:Routine[]=[];photoIndex=0;ocrText='';ocrBusy=false;ocrProgress=0;weeklyChoice:Array<string>=Array(7).fill('');weekdays=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];calendarDate=today();month=today().slice(0,7);plannedRoutine='';
 state:State={routines:[],workouts:[],plans:[]};tab='home';loading=true;busy=false;message='';error='';editor:Routine|null=null;active:Workout|null=null;selected='';demo=false;
 async ngOnInit(){try{await this.token();this.user=await this.request('/auth/me');await this.refresh();this.restoreDraft();}catch{this.loading=false;}this.cdr.detectChanges();}
 async token(){this.csrf=await(await fetch('/api/auth/csrf')).json();}
 async auth(){if(this.busy)return;this.busy=true;try{await this.token();this.user=await this.request('/auth/'+this.authMode,'POST',this.credentials);this.credentials.password='';await this.token();await this.refresh();this.restoreDraft();this.error='';}catch(e){this.error=(e as Error).message;}finally{this.busy=false;this.cdr.detectChanges();}}
 async logout(){try{await this.request('/auth/logout','POST');this.user=null;this.authMode='login';this.credentials={username:'',password:''};this.active=null;this.editor=null;this.state={routines:[],workouts:[],plans:[]};this.message='';await this.token();}catch(e){this.error=(e as Error).message;}this.cdr.detectChanges();}
 async request(path:string,method='GET',body?:unknown){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',[this.csrf.header]:this.csrf.token},body:body?JSON.stringify(body):undefined});if(r.status===401){this.user=null;this.active=null;this.cdr.detectChanges();}if(!r.ok)throw Error(r.status===401?'Sesión caducada o credenciales incorrectas. Inicia sesión de nuevo.':r.status===403?'La petición se ha bloqueado por seguridad. Recarga y vuelve a intentarlo.':r.status===409?'Ese nombre de usuario ya existe.':r.status===429?'Demasiados intentos. Espera 15 minutos.':r.status===400?'Revisa los campos: nombres, series, pesos y repeticiones.':'No se ha guardado. Revisa la conexión y vuelve a intentarlo.');return r.status===204?null:r.json();}
 async refresh(){try{this.state=this.demo?JSON.parse(localStorage.getItem('gymlog-demo')||'{"routines":[],"workouts":[]}'):await this.request('/state');}catch{this.error='No puedo conectar con Spring Boot. Inicia el servidor. Tus cambios no se enviarán hasta que vuelva la conexión.';}finally{this.loading=false;this.selected ||=this.names()[0]||'';this.weeklyChoice=Array.from({length:7},(_,i)=>this.state.weekly?.find(p=>p.weekday===i)?.routineId||'');this.cdr.detectChanges();}}
 persistDemo(){localStorage.setItem('gymlog-demo',JSON.stringify(this.state));}
 uid(){return crypto.randomUUID();}
 draft(){try{if(this.active)localStorage.setItem('gymlog-draft-'+this.user?.id,JSON.stringify(this.active));else localStorage.removeItem('gymlog-draft-'+this.user?.id);}catch{this.error='No se pudo guardar el borrador en este dispositivo.';}this.cdr.detectChanges();}
 restoreDraft(){try{const value=localStorage.getItem('gymlog-draft-'+this.user?.id);if(value)this.active=JSON.parse(value);}catch{this.error='El borrador no se puede leer.';}}
 openEditor(r?:Routine){this.editor=r?structuredClone(r):{name:'',exercises:[{name:'',sets:3,reps:10,repsMax:10,unit:'reps',perSide:false,rir:'2'}]};this.error='';this.cdr.detectChanges();}
 async saveRoutine(){if(!this.editor||this.busy)return;const r=this.editor;if(!r.name.trim()||r.exercises.length===0||r.exercises.some(e=>!e.name.trim()||!Number.isInteger(e.sets)||e.sets<1||e.sets>20||!Number.isInteger(e.reps)||e.reps<1||e.reps>1000||e.repsMax<e.reps||e.repsMax>1000||!/^([0-9]|10|[0-9]-[0-9])$/.test(e.rir))){this.error='Añade nombre y ejercicios. Series: 1–20; repeticiones: 1–100.';return;}this.busy=true;try{if(this.demo){r.id ||=this.uid();this.state.routines=this.state.routines.filter(x=>x.id!==r.id).concat(structuredClone(r));this.persistDemo();}else await this.request('/routines'+(r.id?'/'+r.id:''),r.id?'PUT':'POST',r);this.editor=null;if(this.photoDrafts.length){this.photoDrafts.splice(this.photoIndex,1);this.photoIndex=0;if(this.photoDrafts.length)this.editor=structuredClone(this.photoDrafts[0]);}await this.refresh();this.message='Rutina guardada.';this.error='';}catch(e){this.error=(e as Error).message;}finally{this.busy=false;this.cdr.detectChanges();}}
 async deleteRoutine(r:Routine){if(!confirm('¿Borrar '+r.name+'? Tu historial se conserva.'))return;try{if(this.demo){this.state.routines=this.state.routines.filter(x=>x.id!==r.id);this.persistDemo();}else await this.request('/routines/'+r.id,'DELETE');await this.refresh();}catch(e){this.error=(e as Error).message;}}
 start(r:Routine){if(this.active&&!confirm('Ya tienes una sesión abierta. ¿Descartar el borrador?'))return;this.active={routine:r.name,date:this.calendarDate,notes:'',sets:r.exercises.flatMap(e=>Array.from({length:e.sets},()=>({exercise:e.name,weight:this.lastWeight(e.name),reps:e.reps,unit:e.unit,perSide:e.perSide,rir:Number(e.rir.split('-')[0]),done:false})))};this.tab='train';this.draft();this.error='';this.cdr.detectChanges();}
 lastWeight(name:string){return this.state.workouts.flatMap(w=>w.sets).find(s=>s.exercise===name)?.weight||0;}
 groups(){return [...new Set(this.active?.sets.map(s=>s.exercise)||[])];}
 setsFor(name:string){return this.active?.sets.filter(s=>s.exercise===name)||[];}
 addSet(name:string){const last=this.setsFor(name).at(-1);this.active?.sets.push({exercise:name,weight:last?.weight||0,reps:last?.reps||10,unit:last?.unit||'reps',perSide:last?.perSide||false,rir:last?.rir||0,done:false});this.draft();}
 removeSet(s:SetLog){if(this.active){this.active.sets=this.active.sets.filter(x=>x!==s);this.draft();}}
 completed(){return this.active?.sets.filter(s=>s.done).length||0;}
 async finish(){if(!this.active||this.busy)return;const sets=this.active.sets.filter(s=>s.done);if(!sets.length){this.error='Marca al menos una serie como completada.';return;}if(this.active.date>today()||!this.active.date||sets.some(s=>!validSet(s))){this.error='Revisa fecha, pesos (0–1000 kg, hasta 2 decimales) y repeticiones (1–100).';return;}if(sets.length<this.active.sets.length&&!confirm('Quedan series sin marcar. ¿Guardar solo las '+sets.length+' completadas?'))return;this.busy=true;try{const w={...this.active,sets:sets.map(({done,...s})=>s)};if(this.demo){w.id=this.uid();this.state.workouts.unshift(w);this.persistDemo();}else await this.request('/workouts','POST',w);this.active=null;this.draft();await this.refresh();this.message='Entrenamiento guardado. Un paso más.';this.error='';this.tab='history';}catch(e){this.error=(e as Error).message;}finally{this.busy=false;this.cdr.detectChanges();}}
 cancel(){if(confirm('¿Descartar este entrenamiento sin guardarlo?')){this.active=null;this.draft();}}
 volume(w:Workout){return volume(w.sets);}
 totalVolume(){return this.state.workouts.reduce((n,w)=>n+this.volume(w),0);}
 names(){return [...new Set(this.state.workouts.flatMap(w=>w.sets.map(s=>s.exercise)))];}
 points(){return this.state.workouts.filter(w=>w.sets.some(s=>s.exercise===this.selected)).slice().reverse().map(w=>({date:w.date,weight:Math.max(...w.sets.filter(s=>s.exercise===this.selected).map(s=>s.weight))}));}
 max(){return maximum(this.points());}
 async deleteWorkout(w:Workout){if(!confirm('¿Borrar este entrenamiento? No se puede deshacer.'))return;try{if(this.demo){this.state.workouts=this.state.workouts.filter(x=>x.id!==w.id);this.persistDemo();}else await this.request('/workouts/'+w.id,'DELETE');await this.refresh();}catch(e){this.error=(e as Error).message;}}
 export(){const url=URL.createObjectURL(new Blob([JSON.stringify(this.state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gymlog-'+today()+'.json';a.click();URL.revokeObjectURL(url);}
 seed(){this.editor={name:'Rutina de ejemplo',exercises:[{name:'Press de banca',sets:3,reps:8,repsMax:10,unit:'reps',perSide:false,rir:'2'}]};this.saveRoutine();}
 target(name:string){return this.state.routines.find(r=>r.name===this.active?.routine)?.exercises.find(e=>e.name===name);}
 unitLabel(unit:string){return unit==='m'?'Metros':unit==='s'?'Segundos':'Reps';}
 days(){const [y,m]=this.month.split('-').map(Number);const first=new Date(y,m-1,1);const pad=(first.getDay()+6)%7;const n=new Date(y,m,0).getDate();return [...Array(pad).fill(''),...Array.from({length:n},(_,i)=>`${this.month}-${String(i+1).padStart(2,'0')}`)];}
 planFor(date:string){return this.state.plans.find(p=>p.date===date);}
 routineFor(date:string){const explicit=this.planFor(date);const weekday=(new Date(date+'T12:00:00').getDay()+6)%7;const id=explicit?explicit.routineId:this.state.weekly?.find(p=>p.weekday===weekday)?.routineId;return this.state.routines.find(r=>r.id===id);}
 completedDay(date:string){return this.state.workouts.some(w=>w.date===date);}
 pickDate(date:string){this.calendarDate=date;this.plannedRoutine=this.planFor(date)?.routineId||'';this.cdr.detectChanges();}
 async savePlan(){try{await this.request('/plans','PUT',{date:this.calendarDate,routineId:this.plannedRoutine||null});await this.refresh();this.message='Calendario guardado.';}catch(e){this.error=(e as Error).message;}this.cdr.detectChanges();}
 async clearPlan(){await this.request('/plans/'+this.calendarDate,'DELETE');await this.refresh();this.plannedRoutine='';}
 async importRoutines(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>100000){this.error='Archivo demasiado grande.';return;}let count=0;try{const data=JSON.parse(await file.text());if(!Array.isArray(data)||data.length>20)throw Error('Formato de rutina no válido.');for(const r of data){await this.request('/routines','POST',r);count++;}await this.refresh();this.message=`${count} rutinas importadas a tu cuenta.`;}catch(e){this.error=`${count} rutinas importadas antes del error. ${(e as Error).message}`;await this.refresh();}this.cdr.detectChanges();}
 async saveWeekly(){try{await this.request('/weekly','PUT',this.weeklyChoice.map((routineId,weekday)=>({weekday,routineId:routineId||null})));await this.refresh();this.message='Semana guardada. Cada día verás qué toca.';}catch(e){this.error=(e as Error).message;}this.cdr.detectChanges();}
 weekOf(date:string){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-(d.getDay()+6)%7);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
 weeklyPoints(){const map=new Map<string,number>();for(const p of this.points()){const week=this.weekOf(p.date);map.set(week,Math.max(map.get(week)||0,p.weight));}return [...map].sort(([a],[b])=>a.localeCompare(b)).map(([date,weight])=>({date,weight}));}
 async photo(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>12*1024*1024){this.error='Sube una imagen de hasta 12 MB.';return;}this.ocrBusy=true;this.ocrProgress=0;this.error='';let worker;try{worker=await createWorker('spa',1,{workerPath:'/ocr/worker.min.js',corePath:'/ocr/tesseract-core-simd-lstm.wasm.js',langPath:'/ocr',workerBlobURL:false,logger:m=>{if(m.status==='recognizing text'){this.ocrProgress=Math.round(m.progress*100);this.cdr.detectChanges();}}});const result=await worker.recognize(file);this.ocrText=result.data.text;this.message='Texto leído en este dispositivo. Revísalo antes de convertirlo.';}catch{this.error='No pude leer la foto. Puedes pegar o escribir el texto y convertirlo.';}finally{await worker?.terminate();this.ocrBusy=false;this.cdr.detectChanges();}}
 convertPhoto(){this.photoDrafts=parseRoutines(this.ocrText);this.photoIndex=0;const routine=this.photoDrafts[0];if(!routine){this.error='No encontré series. Corrige el texto: Press banca 3 x 8-10 2 (el último número es RIR).';return;}this.editor=structuredClone(routine);this.tab='routines';this.message='Borrador creado: revisa nombres, series, rangos, unidades y RIR antes de guardar.';this.cdr.detectChanges();}

}
bootstrapApplication(App,{providers:[provideZoneChangeDetection() ]}).catch(console.error);
