CREATE TABLE IF NOT EXISTS routine (id VARCHAR(36) PRIMARY KEY, name VARCHAR(80) NOT NULL);
CREATE TABLE IF NOT EXISTS exercise (id VARCHAR(36) PRIMARY KEY, routine_id VARCHAR(36) NOT NULL REFERENCES routine(id) ON DELETE CASCADE, name VARCHAR(100) NOT NULL, target_sets INT NOT NULL, target_reps INT NOT NULL, position INT NOT NULL);
CREATE TABLE IF NOT EXISTS workout (id VARCHAR(36) PRIMARY KEY, routine_name VARCHAR(80) NOT NULL, trained_on DATE NOT NULL, notes VARCHAR(1000) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS logged_set (workout_id VARCHAR(36) NOT NULL REFERENCES workout(id) ON DELETE CASCADE, exercise_name VARCHAR(100) NOT NULL, position INT NOT NULL, weight DECIMAL(7,2) NOT NULL, reps INT NOT NULL, PRIMARY KEY (workout_id,position));
ALTER TABLE workout ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
